config:
  - command: bug
    template_url: https://github.com/meshtastic/web/blob/main/.github/ISSUE_TEMPLATE/bug.yml
    channel_id:
      - "871553714782081024"
    exclude_fields:
      - screenshots
  - command: feature
    template_url: https://github.com/meshtastic/web/blob/main/.github/ISSUE_TEMPLATE/feature.yml
    channel_id:
      - "871553714782081024"
  - command: bug
    template_url: https://github.com/meshtastic/Meshtastic-Android/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml
    channel_id:
      - "871539863307055134"
  - command: feature
    template_url: https://github.com/meshtastic/Meshtastic-Android/blob/main/.github/ISSUE_TEMPLATE/feature_request.yml
    channel_id:
      - "871539863307055134"